config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  
  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup',  to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  
  resources :recipes do
    resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
    default_scope -> { order(created_at: :desc) }
    validates :user_id, presence: true
    validates :recipe_id, presence: true
    validates :content, presence: true, length: {maximum: 200}
end

app/models/recipe.rb
class Recipe < ApplicationRecord  
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  settings do
    mappings dynamic: false do
      indexes :title, type: :text, analyzer: :english
      indexes :ingredients, type: :text, analyzer: :english
      indexes :description, type: :text, analyzer: :english      
      indexes :vegeterian, type: :boolean
    end
  end

  belongs_to :user
  has_many :comments
  mount_uploader :image, RecipePictureUploader
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 60}
  validates :description, presence: true, length: {maximum: 2000}
  validates :ingredients, presence: true, length: { maximum: 800}
  validates :duration, presence: true
  validate  :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end

  def self.search_generic(query)
    self.search({
      query: {
        bool: {
          must: [
          {
            multi_match: {
              query: query,
              fields: [ :title, :ingredients, :description]
            }
          }]
        }
      }
    })
  end

  def self.search_vegeterian(query)
    self.search({
      query: {
        bool: {
          must: [
          {
            multi_match: {
              query: query,
              fields: [ :title, :ingredients, :description]
            }
          },
          {
            match: {
              vegeterian: true
            }
          }]
        }
      }
    })
  end
  


end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, PictureUploader
    validates :name, presence: true, length: { maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    validate  :image_size
    has_many :comments, dependent:   :destroy
    has_many :recipes, dependent:   :destroy
   
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    private

    def image_size
        if image.size > 5.megabytes
          errors.add(:image, "should be less than 5MB")
        end
      end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url          
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create ]
  
  def create          
    @recipe=Recipe.find(params[:recipe_id])  
    @comment=@recipe.comments.build(comment_params)
    @comment.user=current_user        
    @comment.save
    redirect_to recipe_path(@recipe)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :recipe_id, :user_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    query = params[:search_recipes].presence && params[:search_recipes][:query]  
    if query
      @recipes = Recipe.search_generic(query)      
    end
  end

  def contact
  end

  def about
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, only: [:create, :show, :destroy ]
  before_action :correct_user, only: [:destroy]
 
  def new
    @recipe=Recipe.new    
  end
    
  def create        
    @recipe=current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to user_path(current_user)
    else
      flash.now[:danger]="Recipe not saved!"
      render 'new'
    end
  end

  def show
    @recipe=Recipe.find_by(id: params[:id])        
    @comment=Comment.new 
    @comments=@recipe.comments.paginate(page: params[:page], :per_page => 10)   
  end  
  
  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted!"
    redirect_to user_path(current_user)
  end


  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :ingredients, :image, :servings, :duration, :vegeterian)
  end

  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    redirect_to root_url if @recipe.nil?
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])    
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :destroy, :index, ]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

    def index
      @users=User.paginate(page: params[:page])
    end

    def new
        @user=User.new
    end

    def create
      @user= User.new(user_params)        
      if @user.save
        log_in @user
        flash[:success] = "Welcome to Master Chef!"
        redirect_to @user
      else
        render 'new'
      end
    end

    def show
        @user=User.find(params[:id])
        @recipes= @user.recipes.paginate(page: params[:page], per_page: 10)
    end

    def edit
      @user=User.find(params[:id])
    end
        
    def update
       @user=User.find(params[:id])
       if @user.update_attributes(user_params)
        flash[:success] = "Profile updated!"
        redirect_to @user
       else
        render 'edit'
       end
    end

    def destroy
      User.find(params[:id]).destroy  
      flash[:success] = "User deleted!"    
      redirect_to users_path
    end


    private

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
      end
      
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
  
      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id 
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
    
    def logged_in?      
      !current_user.nil?
    end

    def current_user 
        if session[:user_id]          
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def current_user?(user)
      user == current_user
    end


end

app/helpers/users_helper.rb
module UsersHelper
    


end

app/views/comments/_comment.html.erb
  <li>
    <span class="name"><%= link_to comment.user.name, comment.user %></span>
    <span class="content"><%= comment.content %></span>  
    <span class="timestamp"><%= comment.created_at %></span>      
  </li>

app/views/comments/_comment_form.html.erb
<div class='commentform'>
  <p>Add your comment:</span>
  <%= form_for [@recipe, @comment] do |f|%>  
    <%= f.text_area :content, class: 'content' %>
    <%= f.submit 'Submit',  class: 'btn btn-primary'%>
  <%end%>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    Created by Dimitris Stoios
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>                
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Signup", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MasterChef</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>  
 <!--   <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This is Master Chef. A sample application.</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
  <div>      
      <h1>Be a Master Chef!</h1>      
      <%= image_tag("dishes.jpeg", alt: "Dishes picture", id: "logo")%>
      <h2>
        Discover hundreds of recipes for your favourite dishes!
      </h2>
      <% if logged_in? %>
      <div class="center">
        <%= link_to "Create a recipe", new_recipe_path, class: "btn btn-lg btn-primary" %>     
      </div> 
       Find recipe:  
        <%= render 'shared/search_form' %>        
      <% else %>
      <div class="center">
        <%= link_to "Create a recipe", login_path, class: "btn btn-lg btn-primary" %>
      </div>  
      <% end %>
  </div>
  
  

app/views/recipes/_recipe.html.erb
<li>  
  <%= image_tag(recipe.image.url, size: "50", class: "image") %>  
  <span class="title"><%= link_to recipe.title, recipe_path(recipe) %></span>
  <span class="ingredients"><%= recipe.ingredients %></span>
  <span class="timestamp">
    Created at: <%= recipe.created_at.to_formatted_s(:long_ordinal) %>
    <% if current_user?(recipe.user) %>
      <%= link_to "delete", recipe_path(recipe), method: :delete, data: { confirm: "Do you want to delete this recipe?" } %>
    <% end %>
  </span>
</li>

app/views/recipes/_recipe_form.html.erb
<%= form_for(@recipe) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :ingredients %>
  <%= f.text_area :ingredients, class: 'form-control'  %>
  <%= f.label :description %>
  <%= f.text_area :description, :rows => 10, class: 'form-control'%>
  <%= f.label :servings %>
  <%= f.select :servings, [1, 2, 3, 4, 5, 6], :prompt => 'Select...'%><br><br>
  <%= f.label :duration, "Duration (minutes)" %>
  <%= f.select :duration, [5,10,15,20,25,30,35,45,60,90,120,150,180,210,240,300], :prompt => 'Select...'%><br><br>
  <%= f.label "For vegetarians:" %>
  <%= f.check_box :vegeterian %>
  <p>Upload a photo for your recipe:<%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png'%></p><br>
  <%= f.submit yield(:button_text), class: 'btn btn-primary'%>
<% end %>

app/views/recipes/new.html.erb
<% provide(:button_text, 'Create') %>
<h1> Create your recipe</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'recipe_form' %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class='recipe'>
  
  <h1><%= @recipe.title %></h1>
  
  <% if @recipe.vegeterian %>
    <h2><%= "Vegetarian"%></h2>
  <% end%>

  <%= image_tag @recipe.image.url, class:"image" if @recipe.image? %> 
  
  <h2>Ingredients:</h2>
  <div class="text">
    <%= simple_format(@recipe.ingredients)%>
  </div>
  
  <h2>Instructions:</h2>
  <div class="text">
    <%= simple_format(@recipe.description)%>
  </div>

  <% if @recipe.duration %>
    <p>Duration: <%=@recipe.duration%> minutes</p>
  <%end%>
  
  <% if @recipe.servings %>
    <p>Servings: <%=@recipe.servings%></p>
  <%end%>
  </div>
  <%= render 'comments/comment_form' %>
  
  <% if @recipe.comments.any? %>    
    <ol class="comments">
      <%= render @comments %>
    </ol>
    <%= will_paginate @comments %>
  <% end %>

</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_for :search_recipes, url: root_path, method: :get do |f| %>
  <%= f.text_field :query, value: params[:search_recipes].presence && params[:search_recipes][:query] %>
  <%= f.submit 'Search' %>
<% end %>

<% unless @recipes.nil? %>
  <% if @recipes.empty? %>
    <h2>No recipes found matching your query.</h2>
  <% else %>
    <h2>Search results</h2>

<table >
  <% @recipes.each_slice(3) do |slice| %>   
    <tr>
      <% slice.each do |recipe| %>
        <td> 
          <div class='search-result'>
              <%=link_to  image_tag(recipe.image.url, size: 100), recipe_path(recipe.id) %>
              <span class="title"><%= link_to recipe.title, recipe_path(recipe.id) %></span>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
    
  <% end %>
<% end %>

app/views/users/_user.html.erb
<li>
   <%= image_tag(user.image.url, size: "50") %>    
   <%= link_to user.name, user %>
   <% if current_user.admin? && !current_user?(user) %>
     | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
   <% end %>
</li>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control'%>
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.label :image, "Upload your profile photo" %>  
  <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png'%>
  <%= f.submit yield(:button_text), class: 'btn btn-primary'%>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<%= will_paginate %>
<ul class="users">  
  <%= render @users %>  
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>  
        <%= image_tag @user.image.url size: "100" if @user.image? %>      
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
  <% if @user.recipes.any?%>
    <ol class="recipes">
      <%= render @recipes %>
    </ol>
    <%= will_paginate @recipes %>
  <% end %>
  </div>
</div>